// libs/cv-react/feature-skills/src/lib/components/languages/languages.tsx
import './languages.scss';
import { library } from '@fortawesome/fontawesome-svg-core';
import { LanguageModel } from '@cv-portfolio/data';
import { faStar } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { Space } from '@cv-portfolio/shared/react-ui';

/* eslint-disable-next-line */
export interface LanguagesProps {
  languages: LanguageModel[];
}

export const Languages: React.FC<LanguagesProps> = ({ languages }) => {
  library.add(faStar);

  return (
    <div className="langs-container">
      {languages.map((lang) => (
        <div
          key={lang.langId}
          className={`lang-item ${lang.isNative ? 'lang-native' : null}`}
        >
          <p className="lang-name">
            {lang.langName}
            <Space />
            {lang.isNative && <FontAwesomeIcon icon={faStar} />}
          </p>
          {lang.isNative && <span className="native">Native</span>}
          <p className="lang-desc">{lang.langDesc}</p>
        </div>
      ))}
    </div>
  );
};

// libs/cv-angular/feature-skills/src/lib/components/languages/languages.component.ts
import { Component, Input } from '@angular/core';
import { LanguageModel } from '@cv-portfolio/data';

@Component({
  selector: 'cv-portfolio-languages',
  templateUrl: './languages.component.html',
  styleUrls: ['./languages.component.scss'],
})
export class LanguagesComponent {
  @Input() languages: LanguageModel[] = [];
}

<div class="langs-container">
  <div
    class="lang-item"
    *ngFor="let lang of languages"
    [class]="lang.isNative ? 'lang-native' : ''"
  >
    <p class="lang-name">
      {{ lang.langName }}
      <fa-icon *ngIf="lang.isNative" [icon]="['fas', 'star']"></fa-icon>
    </p>
    <span class="native" *ngIf="lang.isNative">Native</span>
    <p class="lang-desc">{{ lang.langDesc }}</p>
  </div>
</div>
