// libs/cv-react/feature-main/src/components/main/jobs/job/job.tsx
import { Job } from '@cv-portfolio/data';
import './job.scss';

/* eslint-disable-next-line */
export interface JobProps {
  job: Job;
}

const CvReactJob: React.FC<JobProps> = ({ job }) => {
  return (
    <div className="employ">
      <div className={`employ-data ${job.isCurrentJob ? 'current' : ''}`}>
        <p className="employ-header">
          <span className="employ-role-name">{job.roleName}</span>
          at
          <span className="employ-company">{job.company}</span>
          <span className="employ-location">{job.location}</span>
        </p>
        <p className="employ-date-range">
          <span className="date-start_month">
            {job.getDateInfo('start').month}
          </span>
          <span className="date-start_year">
            {job.getDateInfo('start').year}
          </span>
          -
          {job.isCurrentJob ? (
            <span className="present">Present</span>
          ) : (
            <>
              <span className="date-end_month">
                {job.getDateInfo('end').month}
              </span>
              <span className="date-end_year">
                {job.getDateInfo('end').year}
              </span>
            </>
          )}
        </p>
      </div>
    </div>
  );
};

export default CvReactJob;

// libs/cv-angular/feature-main/src/lib/components/main/jobs/job/job.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Job } from '@cv-portfolio/data';

@Component({
  selector: 'cv-portfolio-job',
  templateUrl: './job.component.html',
  styleUrls: ['./job.component.scss'],
})
export class JobComponent {
  @Input()
  job!: Job;
}

<div class="employ">
  <div class="employ-data" [ngClass]="{ current: job.isCurrentJob }">
    <p class="employ-header">
      <span class="employ-role-name">{{ job.roleName }}</span>
      at
      <span class="employ-company">{{ job.company }},</span>
      <span class="employ-location">{{ job.location }}</span>
    </p>
    <p class="employ-date-range">
      <span class="date-start_month">{{ job.getDateInfo('start').month }}</span>
      <span class="date-start_year">{{ job.getDateInfo('start').year }}</span>
      -
      <ng-container *ngIf="!job.isCurrentJob">
        <span class="date-end_month">{{ job.getDateInfo('end').month }}</span>
        <span class="date-end_year">{{ job.getDateInfo('end').year }}</span>
      </ng-container>
      <ng-container *ngIf="job.isCurrentJob">
        <span class="present">Present</span>
      </ng-container>
    </p>
    <div class="employ-functions">
      <ul class="functions-list">
        <li class="function-item" *ngFor="let function of job.jobFunctions">
          {{ function }}
        </li>
      </ul>
    </div>
  </div>
</div>
