// libs/cv-react/feature-skills/src/lib/components/skills/skills.tsx
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { library } from '@fortawesome/fontawesome-svg-core';
import './skills.scss';
import {
  faAngular,
  faCss3,
  faGit,
  faHtml5,
  faJs,
  faReact,
  faSass,
} from '@fortawesome/free-brands-svg-icons';
import { Skill } from './skill/skill';
import { LanguageModel, SkillModel } from '@cv-portfolio/data';
import { useEffect, useState } from 'react';
import { getSkillList } from '../../services/skills.service';
import { faLanguage, faWandSparkles } from '@fortawesome/free-solid-svg-icons';
import {
  Footer,
  Header,
  Loading,
  NoData,
  Space,
} from '@cv-portfolio/shared/react-ui';
import { getLanguages } from '../../services/languages.service';
import { Languages } from '../languages/languages';
import { reorderLanguages } from '@cv-portfolio/utils';
import { finalize, Subject, takeUntil } from 'rxjs';

/* eslint-disable-next-line */
export interface SkillsProps {
  apiUrl: string;
  functionsUrl: string;
}

export const Skills: React.FC<SkillsProps> = ({ apiUrl, functionsUrl }) => {
  const $destroy = new Subject<boolean>();

  library.add(
    faHtml5,
    faJs,
    faCss3,
    faAngular,
    faReact,
    faSass,
    faGit,
    faWandSparkles,
    faLanguage
  );

  const numberOfBars = 4;
  const [skills, setSkills] = useState<SkillModel[]>([]);
  const [languages, setLanguages] = useState<LanguageModel[]>([]);
  const [loadingSkills, setLoadingSkills] = useState(false);
  const [loadingLangs, setLoadingLangs] = useState(false);
  const loadingMessage = {
    skills: 'Loading skills...',
    langs: 'Loading languages...',
  };

  useEffect(() => {
    getSkills();
    getLanguagesList();

    return () => {
      $destroy.next(true);
      $destroy.unsubscribe();
    };
  }, []);

  const getSkills = () => {
    setLoadingSkills(true);
    getSkillList(functionsUrl)
      .pipe(
        finalize(() => setLoadingSkills(false)),
        takeUntil($destroy)
      )
      .subscribe(({ data }) => {
        setSkills(data ? [...data] : []);
      });
  };

  const getLanguagesList = async () => {
    setLoadingLangs(true);
    getLanguages(functionsUrl)
      .pipe(
        finalize(() => setLoadingLangs(false)),
        takeUntil($destroy)
      )
      .subscribe(({ data }) => {
        setLanguages(data ? [...reorderLanguages(data)] : []);
      });
  };

  return (
    <main className="cv-portfolio-skills-container feature-container">
      <Header />
      <section className="working-technologies container">
        <h1 className="title">Technologies on my toolbox</h1>
        <div className="technologies-container">
          <FontAwesomeIcon icon={faHtml5} className="tech-icon html-orange" />
          <FontAwesomeIcon icon={faJs} className="tech-icon js-yellow" />
          <FontAwesomeIcon icon={faCss3} className="tech-icon css-blue" />
          <FontAwesomeIcon icon={faAngular} className="tech-icon angular-red" />
          <FontAwesomeIcon icon={faReact} className="tech-icon react-blue" />
          <FontAwesomeIcon icon={faSass} className="tech-icon rose" />
          <FontAwesomeIcon icon={faGit} className="tech-icon git-orange" />
        </div>
      </section>
      <div className="wrapper">
        <section className="skills container">
          <details>
            <summary>
              <h2 className="section-title cursor-pointer">
                <FontAwesomeIcon icon={faWandSparkles} />
                <Space />
                Skills
              </h2>
            </summary>
            {loadingSkills ? (
              <Loading loadingMessage={loadingMessage.skills} />
            ) : skills.length > 0 ? (
              skills.map((skill) => (
                <Skill
                  key={skill.skillId}
                  skill={skill}
                  numberOfBars={numberOfBars}
                />
              ))
            ) : (
              <NoData noDataText="There are no skills registered." />
            )}
          </details>
        </section>
        <section className="container">
          <details open>
            <summary>
              <h2 className="section-title cursor-pointer">
                <FontAwesomeIcon icon={faLanguage} />
                <Space />
                Languages
              </h2>
            </summary>
            {loadingLangs ? (
              <Loading loadingMessage={loadingMessage.langs} />
            ) : languages.length > 0 ? (
              <Languages languages={languages} />
            ) : (
              <NoData noDataText="There are no languages registered." />
            )}
          </details>
        </section>
      </div>
      <Footer />
    </main>
  );
};

// libs/cv-angular/feature-skills/src/lib/components/skills/skills.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { LanguageModel, SkillModel } from '@cv-portfolio/data';
import { reorderLanguages } from '@cv-portfolio/utils';
import { FaIconLibrary } from '@fortawesome/angular-fontawesome';
import {
  faAngular,
  faCss3,
  faGit,
  faHtml5,
  faJs,
  faReact,
  faSass,
} from '@fortawesome/free-brands-svg-icons';
import {
  faLanguage,
  faStar,
  faWandSparkles,
} from '@fortawesome/free-solid-svg-icons';
import { finalize, Subject, takeUntil } from 'rxjs';
import { LanguagesService } from '../../services/languages.service';
import { SkillsService } from '../../services/skills.service';

@Component({
  selector: 'cv-portfolio-skills',
  templateUrl: './skills.component.html',
  styleUrls: ['./skills.component.scss'],
})
export class SkillsComponent implements OnInit, OnDestroy {
  private $destroy = new Subject<boolean>();
  skills: SkillModel[] = [];
  languages: LanguageModel[] = [];

  numberOfBars = 4;

  isLoading = {
    skills: false,
    langs: false,
  };

  loadingMessage = {
    skills: 'Loading skills...',
    langs: 'Loading languages...',
  };

  constructor(
    private skillsService: SkillsService,
    private langsService: LanguagesService,
    library: FaIconLibrary
  ) {
    library.addIcons(
      faAngular,
      faReact,
      faSass,
      faJs,
      faCss3,
      faHtml5,
      faGit,
      faWandSparkles,
      faLanguage,
      faStar
    );
  }

  ngOnInit(): void {
    this.getSkills();
    this.getLanguages();
  }

  getSkills() {
    this.isLoading.skills = true;
    this.skillsService
      .getSkills()
      .pipe(
        finalize(() => (this.isLoading.skills = false)),
        takeUntil(this.$destroy)
      )
      .subscribe(({ data }) => {
        this.skills = data ? [...data] : [];
      });
  }

  getLanguages() {
    this.isLoading.langs = true;
    this.langsService
      .getLanguages()
      .pipe(
        finalize(() => (this.isLoading.langs = false)),
        takeUntil(this.$destroy)
      )
      .subscribe(({ data }) => {
        this.languages = reorderLanguages(data || []);
      });
  }

  ngOnDestroy(): void {
    this.$destroy.next(true);
    this.$destroy.unsubscribe();
  }
}

<main class="cv-portfolio-skills-container feature-container">
  <cv-portfolio-header></cv-portfolio-header>
  <section class="working-technologies container">
    <h1 class="title">Technologies on my toolbox</h1>
    <div class="technologies-container">
      <fa-icon
        class="tech-icon html-orange"
        [icon]="['fab', 'html5']"
      ></fa-icon>
      <fa-icon class="tech-icon js-yellow" [icon]="['fab', 'js']"></fa-icon>
      <fa-icon class="tech-icon css-blue" [icon]="['fab', 'css3']"></fa-icon>
      <fa-icon
        class="tech-icon angular-red"
        [icon]="['fab', 'angular']"
      ></fa-icon>
      <fa-icon class="tech-icon react-blue" [icon]="['fab', 'react']"></fa-icon>
      <fa-icon class="tech-icon rose" [icon]="['fab', 'sass']"></fa-icon>
      <fa-icon class="tech-icon git-orange" [icon]="['fab', 'git']"></fa-icon>
    </div>
  </section>
  <div class="wrapper">
    <section class="skills container">
      <details>
        <summary>
          <h2 class="section-title cursor-pointer">
            <fa-icon [icon]="['fas', 'wand-sparkles']"></fa-icon>
            Skills
          </h2>
        </summary>
        <ng-container *ngIf="!isLoading.skills; else loadingSkills">
          <ng-container *ngIf="skills.length > 0; else noData">
            <cv-portfolio-skill
              *ngFor="let skill of skills"
              [skill]="skill"
              [numberOfBars]="numberOfBars"
            ></cv-portfolio-skill>
          </ng-container>
          <ng-template #noData>
            <cv-portfolio-no-data
              noDataText="There are no skills registered."
            ></cv-portfolio-no-data>
          </ng-template>
        </ng-container>
      </details>
    </section>
    <section class="languages container">
      <details open>
        <summary>
          <h2 class="section-title cursor-pointer">
            <fa-icon [icon]="['fas', 'language']"></fa-icon>
            Languages
          </h2>
        </summary>
        <ng-container *ngIf="!isLoading.langs; else loadingLangs">
          <ng-container *ngIf="languages.length > 0; else noDataLangs">
            <cv-portfolio-languages
              [languages]="languages"
            ></cv-portfolio-languages>
          </ng-container>
          <ng-template #noDataLangs>
            <cv-portfolio-no-data
              noDataText="There are no languages registered."
            ></cv-portfolio-no-data>
          </ng-template>
        </ng-container>
      </details>
    </section>
  </div>
  <cv-portfolio-footer></cv-portfolio-footer>
</main>
<ng-template #loadingSkills>
  <cv-portfolio-loading
    [loadingMessage]="loadingMessage.skills"
  ></cv-portfolio-loading>
</ng-template>
<ng-template #loadingLangs>
  <cv-portfolio-loading
    [loadingMessage]="loadingMessage.langs"
  ></cv-portfolio-loading>
</ng-template>
