// libs/cv-react/feature-main/src/components/footer/footer.tsx
import './footer.scss';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { library } from '@fortawesome/fontawesome-svg-core';
import { faReact } from '@fortawesome/free-brands-svg-icons';

/* eslint-disable-next-line */
export interface FooterProps {}

const Footer: React.FC<FooterProps> = () => {
  library.add(faReact);
  return (
    <footer className="cv-portfolio-footer">
      <img src="/assets/images/logo.png" alt="logo" className="logo" />
      <FontAwesomeIcon icon={faReact} size="2x" className="icon-powered" />
      <p className="powered">Powered by Nx</p>
    </footer>
  );
};

export default Footer;

// libs/shared/ui/src/lib/angular-components/footer/footer.component.ts
import { Component } from '@angular/core';
import { FaIconLibrary } from '@fortawesome/angular-fontawesome';
import { faAngular } from '@fortawesome/free-brands-svg-icons';

@Component({
  selector: 'cv-portfolio-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss'],
})
export class FooterComponent {
  constructor(library: FaIconLibrary) {
    library.addIcons(faAngular);
  }
}
