// libs/cv-angular/feature-main/src/lib/components/main/main.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { JobModel } from '@cv-portfolio/data';
import { FaIconLibrary } from '@fortawesome/angular-fontawesome';
import {
  faAddressCard,
  faFire,
  faFolderOpen,
} from '@fortawesome/free-solid-svg-icons';
import { faAngular } from '@fortawesome/free-brands-svg-icons';
import { Subject, takeUntil } from 'rxjs';
import { JobsService } from '../../services/jobs.service';

@Component({
  selector: 'cv-portfolio-main',
  templateUrl: './main.component.html',
  styleUrls: ['./main.component.scss'],
})
export class MainComponent implements OnInit, OnDestroy {
  private $destroy = new Subject<boolean>();

  jobs: JobModel[] = [];

  constructor(private jobsService: JobsService, library: FaIconLibrary) {
    library.addIcons(faAddressCard, faFolderOpen, faFire, faAngular);
  }

  ngOnInit(): void {
    this.getJobsHistory();
  }

  getJobsHistory() {
    this.jobsService
      .getJobHistory()
      .pipe(takeUntil(this.$destroy))
      .subscribe(({ data }) => {
        this.jobs = data ? [...data] : [];
      });
  }

  ngOnDestroy(): void {
    this.$destroy.next(true);
    this.$destroy.unsubscribe();
  }
}

<cv-portfolio-header-main></cv-portfolio-header-main>
<div class="cv-portfolio-main-container">
  <section id="about-me" class="about container">
    <h2 class="section-title">
      <fa-icon [icon]="['fas', 'address-card']"></fa-icon>
      About me
    </h2>
    <h3 class="role">Frontend Developer</h3>
    <p class="introduction">
      Web developer with five years of experience in front-end development,
      focused in making high scalable web applications with the best practices
      using the angular framework, also with abilities of working with agile
      methodologies and self learning.
    </p>
  </section>
  <section id="employment-history" class="container">
    <h2 class="section-title">
      <fa-icon [icon]="['fas', 'folder-open']"></fa-icon>
      Jobs
    </h2>
    <cv-portfolio-jobs [jobs]="jobs"></cv-portfolio-jobs>
  </section>
</div>

// libs/cv-react/feature-main/src/components/main/main.tsx
import './main.scss';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faAddressCard,
  faFire,
  faFolderOpen,
} from '@fortawesome/free-solid-svg-icons';
import Jobs from './jobs/jobs';
import { useEffect, useState } from 'react';
import { getJobHistory } from '../../services/jobs.service';
import { JobModel } from '@cv-portfolio/data';

/* eslint-disable-next-line */
export interface MainProps {}

export function Main(props: MainProps) {
  library.add(faAddressCard, faFolderOpen, faFire);
  const [jobs, setJobs] = useState<JobModel[]>([]);
  useEffect(() => {
    getHistory();
  }, []);

  const getHistory = async () => {
    const {
      data: { data },
    } = await getJobHistory();
    setJobs(data ? [...data] : []);
  };

  return (
    <div className="cv-portfolio-main-container">
      <section id="about-me" className="about container">
        <h2 className="section-title">
          <FontAwesomeIcon icon={faAddressCard} className="icon" />
          About me
        </h2>
        <h3 className="role">Frontend Developer</h3>
        <p className="introduction">
          Web developer with five years of experience in front-end development,
          focused in making high scalable web applications with the best
          practices using the angular framework, also with abilities of working
          with agile methodologies and self learning.
        </p>
      </section>
      <section id="employment-history" className="container">
        <h2 className="section-title">
          <FontAwesomeIcon icon={faFolderOpen} className="icon" />
          Jobs
        </h2>
        <Jobs jobs={jobs} />
      </section>
    </div>
  );
}

export default Main;
