// libs/cv-angular/feature-skills/src/lib/components/skills/skill/skill.component.ts
import { Component, Input } from '@angular/core';
import { SkillModel } from '@cv-portfolio/data';

@Component({
  selector: 'cv-portfolio-skill',
  templateUrl: './skill.component.html',
  styleUrls: ['./skill.component.scss'],
})
export class SkillComponent {
  @Input() skill: SkillModel = {
    skillName: '',
    skillLevel: 0,
    skillId: '',
  };

  @Input() numberOfBars = 0;
}

<div
  class="skill"
  [style.grid-template-columns]="'repeat(' + numberOfBars + ', 1fr)'"
>
  <span class="skill-name"
    >{{ skill.skillName }}
    <span class="skill-level-num">({{ skill.skillLevel }})</span>
  </span>
  <cv-portfolio-skill-level
    *ngFor="let level of numberOfBars | fill; let i = index"
    [level]="skill.skillLevel"
    [base]="((i + 1) * 100) / numberOfBars"
  ></cv-portfolio-skill-level>
  <!-- <cv-portfolio-skill-level
    [level]="skill.skillLevel"
    [base]="25"
  ></cv-portfolio-skill-level>
  <cv-portfolio-skill-level
    [level]="skill.skillLevel"
    [base]="50"
  ></cv-portfolio-skill-level>
  <cv-portfolio-skill-level
    [level]="skill.skillLevel"
    [base]="75"
  ></cv-portfolio-skill-level>
  <cv-portfolio-skill-level
    [level]="skill.skillLevel"
    [base]="100"
  ></cv-portfolio-skill-level> -->
</div>

// libs/cv-react/feature-skills/src/lib/components/skills/skill/skill.tsx
import { SkillModel } from '@cv-portfolio/data';
import SkillLevel from './skill-level/skill-level';
import './skill.scss';

/* eslint-disable-next-line */
export interface SkillProps {
  skill: SkillModel;
  numberOfBars: number;
}

export const Skill: React.FC<SkillProps> = ({ skill, numberOfBars }) => {
  const gridColumns = {
    gridTemplateColumns: `repeat(${numberOfBars}, 1fr)`,
  };
  const skillBase = (i: number) => ((i + 1) * 100) / numberOfBars;
  return (
    <div className="skill" style={gridColumns}>
      <span className="skill-name">
        {skill.skillName}
        <span> </span>
        <span className="skill-level-num">({skill.skillLevel})</span>
      </span>
      {[...Array(numberOfBars)].map((level, i) => (
        <SkillLevel
          key={`${skill.skillId}-${skillBase(i)}`}
          numberOfBars={numberOfBars}
          level={skill.skillLevel}
          base={skillBase(i)}
        />
      ))}
    </div>
  );
};
