// libs/shared/ui/src/lib/angular-components/loading/loading.component.ts
import { Component, Input } from '@angular/core';
import { FaIconLibrary } from '@fortawesome/angular-fontawesome';
import { faCircleNotch } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'cv-portfolio-loading',
  templateUrl: './loading.component.html',
  styleUrls: ['./loading.component.scss'],
})
export class LoadingComponent {
  @Input() loadingMessage = '';

  constructor(private library: FaIconLibrary) {
    library.addIcons(faCircleNotch);
  }
}

<div class="loading-container">
  <fa-icon [icon]="['fas', 'circle-notch']" size="3x" [spin]="true"></fa-icon>
  <p class="loading-message">{{ loadingMessage }}</p>
</div>

// libs/shared/react-ui/src/lib/components/loading/loading.tsx
import './loading.scss';
import { library } from '@fortawesome/fontawesome-svg-core';
import { faCircleNotch } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

/* eslint-disable-next-line */
export interface LoadingProps {
  loadingMessage: string;
}

export const Loading: React.FC<LoadingProps> = ({ loadingMessage }) => {
  library.add(faCircleNotch);
  return (
    <div className="loading-container">
      <FontAwesomeIcon icon={faCircleNotch} spin={true} size="3x" />
      <p className="loading-message">{loadingMessage}</p>
    </div>
  );
};
