// libs/cv-react/feature-main/src/components/main/jobs/jobs.tsx
import { JobModel } from '@cv-portfolio/data';
import CvReactJob from './job/job';
import './jobs.scss';

/* eslint-disable-next-line */
export interface JobsProps {
  jobs: JobModel[];
}

const Jobs: React.FC<JobsProps> = ({ jobs }) => {
  return (
    <div className="employ-container">
      {jobs.length > 0 &&
        jobs.map((job) => <CvReactJob key={job.roleName} job={job} />)}
      {jobs.length === 0 && (
        <div className="no-jobs-container">
          <span className="no-jobs-text">There are no jobs registered.</span>
        </div>
      )}
    </div>
  );
};

export default Jobs;

// libs/cv-angular/feature-main/src/lib/components/main/jobs/jobs.component.ts
import { Component, Input } from '@angular/core';
import { JobModel } from '@cv-portfolio/data';

@Component({
  selector: 'cv-portfolio-jobs',
  templateUrl: './jobs.component.html',
  styleUrls: ['./jobs.component.scss'],
})
export class JobsComponent {
  @Input() jobs: JobModel[] = [];
}

<div class="employ-container">
  <ng-container *ngIf="jobs.length > 0; else no_jobs">
    <cv-portfolio-job *ngFor="let job of jobs" [job]="job"></cv-portfolio-job>
  </ng-container>
  <ng-template #no_jobs>
    <div class="no-jobs-container">
      <span class="no-jobs-text">There are no jobs registered.</span>
    </div>
  </ng-template>
</div>
