// libs/cv-angular/feature-skills/src/lib/components/skills/skill/skill-level/skill-level.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'cv-portfolio-skill-level',
  templateUrl: './skill-level.component.html',
  styleUrls: ['./skill-level.component.scss'],
})
export class SkillLevelComponent {
  @Input() level = -1;
  @Input() base = 0;
  @Input() numberOfBars = 4;

  getWidth() {
    if (
      this.base - 100 / this.numberOfBars < this.level &&
      this.level <= this.base
    ) {
      const diff = this.level - (this.base - 100 / this.numberOfBars);
      return `${diff * this.numberOfBars}%`;
    } else if (this.base > this.level) {
      return 0;
    } else {
      return '100%';
    }
  }
}

<div class="skill-level" [style]="{ width: getWidth() }"></div>

// libs/cv-react/feature-skills/src/lib/components/skills/skill/skill-level/skill-level.tsx
import './skill-level.scss';
/* eslint-disable-next-line */
export interface SkillLevelProps {
  level: number;
  base: number;
  numberOfBars: number;
}

export const SkillLevel: React.FC<SkillLevelProps> = ({
  level,
  base,
  numberOfBars,
}) => {
  const getWidth = () => {
    if (base - 100 / numberOfBars < level && level <= base) {
      const diff = level - (base - 100 / numberOfBars);
      return `${diff * numberOfBars}%`;
    } else if (base > level) {
      return 0;
    } else {
      return '100%';
    }
  };
  const style = {
    width: getWidth(),
  };
  return <div className="skill-level" style={style}></div>;
};

export default SkillLevel;
