// libs/shared/ui/src/lib/nav/nav.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'cv-portfolio-nav',
  templateUrl: './nav.component.html',
  styleUrls: ['./nav.component.scss'],
})
export class NavComponent {
  menuOpen = false;

  toggleMenu() {
    this.menuOpen = !this.menuOpen;
  }
}

<nav class="cv-navbar">
  <img src="/assets/images/logo.png" alt="logo" class="logo" />
  <!-- Hambuger Menu -->
  <button
    type="button"
    class="hamburger"
    [ngClass]="{ open: menuOpen }"
    *ngIf="!menuOpen"
    (click)="toggleMenu()"
  >
    <span class="hamburger-top"></span>
    <span class="hamburger-middle"></span>
    <span class="hamburger-bottom"></span>
  </button>
  <div class="menu" *ngIf="menuOpen">
    <button
      type="button"
      class="hamburger"
      [ngClass]="{ open: menuOpen }"
      (click)="toggleMenu()"
    >
      <span class="hamburger-top"></span>
      <span class="hamburger-middle"></span>
      <span class="hamburger-bottom"></span>
    </button>
    <div class="menu-container">
      <ul class="menu-items">
        <a href="#about" class="menu-link" (click)="toggleMenu()">
          <li class="menu-item">About</li>
        </a>
        <a href="#employment-history" class="menu-link" (click)="toggleMenu()">
          <li class="menu-item">Employment History</li>
        </a>
      </ul>
    </div>
  </div>

  <!-- Nav Menu for Large Screens -->
  <ul class="nav-items">
    <a href="#about" class="nav-link">
      <li class="nav-item">About</li>
    </a>
    <a href="#employment-history" class="nav-link">
      <li class="nav-item">Employment History</li>
    </a>
  </ul>
</nav>

// libs/cv-react/feature-main/src/components/header/nav/nav.tsx
import { useState } from 'react';
import './nav.scss';

/* eslint-disable-next-line */
export interface NavProps {}

const Nav: React.FC<NavProps> = (props: NavProps) => {
  const [menuOpen, setMenuOpen] = useState(false);

  const toggleMenu = () => {
    setMenuOpen(!menuOpen);
  };

  return (
    <nav className="cv-navbar">
      <img src="/assets/images/logo.png" alt="logo" className="logo" />
      {!menuOpen ? (
        <button
          type="button"
          className={`hamburger ${menuOpen ? 'open' : ''}`}
          onClick={toggleMenu}
        >
          <span className="hamburger-top"></span>
          <span className="hamburger-middle"></span>
          <span className="hamburger-bottom"></span>
        </button>
      ) : (
        <div className="menu">
          <button
            type="button"
            className={`hamburger ${menuOpen ? 'open' : ''}`}
            onClick={toggleMenu}
          >
            <span className="hamburger-top"></span>
            <span className="hamburger-middle"></span>
            <span className="hamburger-bottom"></span>
          </button>
          <div className="menu-container">
            <ul className="menu-items">
              <a href="#about" className="menu-link" onClick={toggleMenu}>
                <li className="menu-item">About</li>
              </a>
              <a
                href="#employment-history"
                className="menu-link"
                onClick={toggleMenu}
              >
                <li className="menu-item">Employment History</li>
              </a>
            </ul>
          </div>
        </div>
      )}
      <ul className="nav-items">
        <a href="#about" className="nav-link">
          <li className="nav-item">About</li>
        </a>
        <a href="#employment-history" className="nav-link">
          <li className="nav-item">Employment History</li>
        </a>
      </ul>
    </nav>
  );
};

export default Nav;
