// libs/shared/ui/src/lib/angular-components/nav/nav.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'cv-portfolio-nav',
  templateUrl: './nav.component.html',
  styleUrls: ['./nav.component.scss'],
})
export class NavComponent {
  menuOpen = false;

  constructor(private router: Router) {}

  toggleMenu() {
    this.menuOpen = !this.menuOpen;
  }

  goToHome() {
    this.router.navigate(['/home']);
  }
}

<nav class="cv-navbar">
  <img
    src="/assets/images/logo.png"
    alt="logo"
    class="logo"
    (click)="goToHome()"
  />
  <!-- Hambuger Menu -->
  <button
    type="button"
    class="hamburger"
    [ngClass]="{ open: menuOpen }"
    *ngIf="!menuOpen"
    (click)="toggleMenu()"
  >
    <span class="hamburger-top"></span>
    <span class="hamburger-middle"></span>
    <span class="hamburger-bottom"></span>
  </button>
  <div class="menu" *ngIf="menuOpen">
    <button
      type="button"
      class="hamburger"
      [ngClass]="{ open: menuOpen }"
      (click)="toggleMenu()"
    >
      <span class="hamburger-top"></span>
      <span class="hamburger-middle"></span>
      <span class="hamburger-bottom"></span>
    </button>
    <div class="menu-container">
      <ul class="menu-items">
        <li class="menu-item">
          <a
            [routerLink]="['/home']"
            routerLinkActive="router-link-active"
            class="menu-link"
            (click)="toggleMenu()"
          >
            Home
          </a>
        </li>
        <li class="menu-item">
          <a
            [routerLink]="['/skills']"
            routerLinkActive="router-link-active"
            class="menu-link"
            (click)="toggleMenu()"
            >Skills</a
          >
        </li>
      </ul>
    </div>
  </div>

  <!-- Nav Menu for Large Screens -->
  <ul class="nav-items">
    <li class="nav-item">
      <a
        [routerLink]="['/home']"
        routerLinkActive="router-link-active"
        class="nav-link"
      >
        Home
      </a>
    </li>
    <li class="nav-item">
      <a
        [routerLink]="['/skills']"
        routerLinkActive="router-link-active"
        class="nav-link"
        >Skills</a
      >
    </li>
  </ul>
</nav>

// libs/shared/react-ui/src/lib/components/header/nav/nav.tsx
import { useState } from 'react';
import { Link, NavLink } from 'react-router-dom';
import './nav.scss';

/* eslint-disable-next-line */
export interface NavProps {}

const Nav: React.FC<NavProps> = (props: NavProps) => {
  const [menuOpen, setMenuOpen] = useState(false);

  const toggleMenu = () => {
    setMenuOpen(!menuOpen);
  };

  return (
    <nav className="cv-navbar">
      <img src="/assets/images/logo.png" alt="logo" className="logo" />
      {!menuOpen ? (
        <button
          type="button"
          className={`hamburger ${menuOpen ? 'open' : ''}`}
          onClick={toggleMenu}
        >
          <span className="hamburger-top"></span>
          <span className="hamburger-middle"></span>
          <span className="hamburger-bottom"></span>
        </button>
      ) : (
        <div className="menu">
          <button
            type="button"
            className={`hamburger ${menuOpen ? 'open' : ''}`}
            onClick={toggleMenu}
          >
            <span className="hamburger-top"></span>
            <span className="hamburger-middle"></span>
            <span className="hamburger-bottom"></span>
          </button>
          <div className="menu-container">
            <ul className="menu-items">
              <li className="menu-item">
                <NavLink
                  to="/"
                  className={({ isActive }) =>
                    isActive ? 'router-link-active menu-link' : 'menu-link'
                  }
                  onClick={toggleMenu}
                >
                  Home
                </NavLink>
              </li>
              <li className="menu-item">
                <NavLink
                  to="/skills"
                  className={({ isActive }) =>
                    isActive ? 'router-link-active menu-link' : 'menu-link'
                  }
                  onClick={toggleMenu}
                >
                  Skills
                </NavLink>
              </li>
            </ul>
          </div>
        </div>
      )}
      <ul className="nav-items">
        <li className="nav-item">
          <NavLink
            to="/"
            className={({ isActive }) =>
              isActive ? 'router-link-active nav-link' : 'nav-link'
            }
          >
            Home
          </NavLink>
        </li>
        <li className="nav-item">
          <NavLink
            to="/skills"
            className={({ isActive }) =>
              isActive ? 'router-link-active nav-link' : 'nav-link'
            }
          >
            Skills
          </NavLink>
        </li>
      </ul>
    </nav>
  );
};

export default Nav;
